### ISSUE TITLE
Algo gebrochen?

### ISSUE THREAD

**Issue by polygamma** [Habba5/Heuristic-solution-of-Ishop#2]
Hallo!

Beim Studium Ihrer Thesis ist mir aufgefallen, dass Ihr sogenannter Algorithmus nicht richtig zu funktionieren scheint. Ich bin persönlich höchstinteressiert an der Karte Akroan Crusader und wollte mir diese 4x kaufen. Ihr Programm liefert das folgende Ergebnis:

![screenshot from 2018-01-12 20-36-31](https://user-images.githubusercontent.com/20651500/34892159-7dada02a-f7d8-11e7-8755-387ce60aec34.png)

Dies ist trivial nicht optimal! Mein Gemütszustand nähert sich einer Schranke, jedoch keiner oberen Schranke, falls Sie verstehen.

Grüße,
Knecht Ruprecht

**Comment by Habba5** [comment]
Fixxed some Commits ago. Playset should now be addressed correctly.
